# Treinando modelos

Normalmente os dados de bioacústica são desbalanceados. É comum que os animais que os ecologos e biológos tem interesse sejam animais em extinção.

A lib OpenSoundscape sugere tentar o balancear os dados ao máximo. A próxima célula faz upsample (repetindo amostras de dados) para igualar.

In [1]:
from pathlib import Path

import pandas as pd

from opensoundscape.data_selection import resample

/home/italo/open/shazam-da-natureza/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train_file = Path("train.csv")
assert train_file.exists(), "Arquivo de treino não encontrado. Verifique que ele foi criado no '02_particionando_dados.ipynb'"

In [10]:
valid_file = Path("valid.csv")
assert valid_file.exists(), "Arquivo de validação não encontrado. Verifique que ele foi criado no '02_particionando_dados.ipynb'"

In [3]:
train_df = pd.read_csv(train_file, index_col=["file", "start_time", "end_time"])
train_df.head()

,,,NOCA,EATO,SCTA,BAWW,BCCH,AMCR,NOFL
file,start_time,end_time,,,,,,,
../data/mp3_Files/Recording_1/Recording_1_Segment_21.mp3,186.0,189.0,False,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_29.mp3,75.0,78.0,False,False,False,False,False,True,False
../data/mp3_Files/Recording_1/Recording_1_Segment_30.mp3,186.0,189.0,False,False,False,False,False,True,False
../data/mp3_Files/Recording_1/Recording_1_Segment_12.mp3,78.0,81.0,False,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_18.mp3,234.0,237.0,True,True,False,False,False,False,False

In [13]:
valid_df = pd.read_csv(train_file, index_col=["file", "start_time", "end_time"])
valid_df.head()

,,,NOCA,EATO,SCTA,BAWW,BCCH,AMCR,NOFL
file,start_time,end_time,,,,,,,
../data/mp3_Files/Recording_1/Recording_1_Segment_21.mp3,186.0,189.0,False,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_29.mp3,75.0,78.0,False,False,False,False,False,True,False
../data/mp3_Files/Recording_1/Recording_1_Segment_30.mp3,186.0,189.0,False,False,False,False,False,True,False
../data/mp3_Files/Recording_1/Recording_1_Segment_12.mp3,78.0,81.0,False,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_18.mp3,234.0,237.0,True,True,False,False,False,False,False

In [6]:
balanced_train_df = resample(train_df, n_samples_per_class=800, random_state=0)
balanced_train_df.head()

,,,NOCA,EATO,SCTA,BAWW,BCCH,AMCR,NOFL
file,start_time,end_time,,,,,,,
../data/mp3_Files/Recording_1/Recording_1_Segment_18.mp3,234.0,237.0,True,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_06.mp3,93.0,96.0,True,True,False,False,False,False,False
../data/mp3_Files/Recording_2/Recording_2_Segment_05.mp3,237.0,240.0,True,False,False,False,True,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_19.mp3,90.0,93.0,True,True,False,False,False,False,False
../data/mp3_Files/Recording_1/Recording_1_Segment_16.mp3,255.0,258.0,True,True,False,False,False,False,False

In [18]:
from opensoundscape import CNN

architecture = "resnet34"

class_list = list(train_df.columns)

model = CNN(
    architecture=architecture,
    classes=class_list,
    sample_duration=3,
    sample_rate=32000,
    device="cpu",
)

In [19]:
model.device

device(type='cpu')

In [8]:
checkpoint_folder = Path("model_training_checkpoints")
checkpoint_folder.mkdir(exist_ok=True)

In [ ]:
model.train(
    balanced_train_df,
    valid_df,
    steps=30,
    batch_size=64,
    log_interval=100,
    num_workers=1,
    wandb_session=None,
    save_path=checkpoint_folder,
)

  0%|                                                                                                                                                         | 0/30 [00:00<?, ?it/s]

Step: 0/30 (0.0%)
	Running Average Loss: 0.800
	Most Recent Step Loss: 0.800

Validation.

  0%|                                                                                                                                                         | 0/72 [00:00<?, ?it/s]
  1%|██                                                                                                                                               | 1/72 [00:07<09:08,  7.73s/it]
  3%|████                                                                                                                                             | 2/72 [00:13<07:56,  6.81s/it]
  4%|██████                                                                                                                                           | 3/72 [00:20<07:29,  6.51s/it]
  6%|████████                                                                                                                                         | 4/72 [00:26<07:14,  6.40s/it]
  7%|██████████                                                                                                                                       | 5/72 [00:32<07:01,  6.29s/it]
  8%|████████████                                                                                                                                     | 6/72 [00:38<06:49,  6.20s/it]
 10%|██████████████                                                                                                                                   | 7/72 [00:44<06:41,  6.18s/it]
 11%|████████████████                                                                                                                                 | 8/72 [00:50<06:30,  6.11s/it]
 12%|██████████████████▏                                                                                                                              | 9/72 [00:56<06:21,  6.06s/it]
 14%|████████████████████                                                                                                                            | 10/72 [01:02<06:14,  6.04s/it]
 15%|██████████████████████                                                                                                                          | 11/72 [01:08<06:08,  6.04s/it]
 17%|████████████████████████                                                                                                                        | 12/72 [01:14<06:02,  6.04s/it]
 18%|██████████████████████████                                                                                                                      | 13/72 [01:20<05:54,  6.02s/it]
 19%|████████████████████████████                                                                                                                    | 14/72 [01:26<05:48,  6.00s/it]
 21%|██████████████████████████████                                                                                                                  | 15/72 [01:32<05:42,  6.00s/it]
 22%|████████████████████████████████                                                                                                                | 16/72 [01:38<05:36,  6.01s/it]
 24%|██████████████████████████████████                                                                                                              | 17/72 [01:44<05:33,  6.06s/it]
 25%|████████████████████████████████████                                                                                                            | 18/72 [01:50<05:26,  6.04s/it]
 26%|██████████████████████████████████████                                                                                                          | 19/72 [01:56<05:19,  6.03s/it]
 28%|████████████████████████████████████████                                                                                                        | 20/72 [02:02<05:15,  6.07s/it]
 29%|██████████████████████████████████████████                                                                                                      | 21/72 [02:08<05:11,  6.10s/it]
 31%|████████████████████████████████████████████                                                                                                    | 22/72 [02:15<05:10,  6.21s/it]
 32%|██████████████████████████████████████████████                                                                                                  | 23/72 [02:21<05:03,  6.20s/it]
 33%|████████████████████████████████████████████████                                                                                                | 24/72 [02:27<04:56,  6.18s/it]
 35%|██████████████████████████████████████████████████                                                                                              | 25/72 [02:33<04:49,  6.17s/it]
 36%|████████████████████████████████████████████████████                                                                                            | 26/72 [02:41<05:05,  6.64s/it]
 38%|██████████████████████████████████████████████████████                                                                                          | 27/72 [02:48<04:57,  6.60s/it]
 39%|████████████████████████████████████████████████████████                                                                                        | 28/72 [02:54<04:47,  6.54s/it]
 40%|██████████████████████████████████████████████████████████                                                                                      | 29/72 [03:00<04:38,  6.48s/it]
 42%|████████████████████████████████████████████████████████████                                                                                    | 30/72 [03:07<04:29,  6.41s/it]
 43%|██████████████████████████████████████████████████████████████                                                                                  | 31/72 [03:13<04:20,  6.36s/it]
 44%|████████████████████████████████████████████████████████████████                                                                                | 32/72 [03:19<04:13,  6.33s/it]
 46%|██████████████████████████████████████████████████████████████████                                                                              | 33/72 [03:25<04:02,  6.23s/it]
 47%|████████████████████████████████████████████████████████████████████                                                                            | 34/72 [03:31<03:53,  6.16s/it]
 49%|██████████████████████████████████████████████████████████████████████                                                                          | 35/72 [03:37<03:47,  6.14s/it]
 50%|████████████████████████████████████████████████████████████████████████                                                                        | 36/72 [03:43<03:40,  6.14s/it]
 51%|██████████████████████████████████████████████████████████████████████████                                                                      | 37/72 [03:49<03:34,  6.13s/it]
 53%|████████████████████████████████████████████████████████████████████████████                                                                    | 38/72 [03:55<03:27,  6.09s/it]
 54%|██████████████████████████████████████████████████████████████████████████████                                                                  | 39/72 [04:02<03:21,  6.10s/it]
 56%|████████████████████████████████████████████████████████████████████████████████                                                                | 40/72 [04:08<03:14,  6.07s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████                                                              | 41/72 [04:14<03:07,  6.06s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████                                                            | 42/72 [04:20<03:02,  6.07s/it]
 60%|██████████████████████████████████████████████████████████████████████████████████████                                                          | 43/72 [04:26<02:55,  6.06s/it]
 61%|████████████████████████████████████████████████████████████████████████████████████████                                                        | 44/72 [04:32<02:50,  6.11s/it]
 62%|██████████████████████████████████████████████████████████████████████████████████████████                                                      | 45/72 [04:38<02:46,  6.15s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████                                                    | 46/72 [04:45<02:41,  6.21s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████                                                  | 47/72 [04:51<02:35,  6.20s/it]
 67%|████████████████████████████████████████████████████████████████████████████████████████████████                                                | 48/72 [04:57<02:27,  6.16s/it]
 68%|██████████████████████████████████████████████████████████████████████████████████████████████████                                              | 49/72 [05:03<02:21,  6.17s/it]
 69%|████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 50/72 [05:09<02:14,  6.13s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 51/72 [05:15<02:08,  6.11s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 52/72 [05:21<02:02,  6.10s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 53/72 [05:27<01:56,  6.12s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 54/72 [05:34<01:50,  6.14s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 55/72 [05:40<01:43,  6.11s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 56/72 [05:46<01:38,  6.15s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 57/72 [05:52<01:31,  6.13s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 58/72 [05:58<01:25,  6.12s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 59/72 [06:04<01:19,  6.09s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 60/72 [06:10<01:12,  6.08s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 61/72 [06:16<01:06,  6.07s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 62/72 [06:22<01:00,  6.08s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 63/72 [06:28<00:54,  6.08s/it]
 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 64/72 [06:34<00:48,  6.06s/it]
 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 65/72 [06:40<00:42,  6.06s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 66/72 [06:47<00:36,  6.10s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 67/72 [06:53<00:30,  6.08s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 68/72 [06:59<00:24,  6.06s/it]
 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 69/72 [07:05<00:18,  6.08s/it]
 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 70/72 [07:11<00:12,  6.08s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 71/72 [07:17<00:06,  6.02s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72/72 [07:21<00:00,  6.13s/it]
/home/italo/open/shazam-da-natureza/venv/lib/python3.13/site-packages/opensoundscape/ml/cnn.py:1039: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  targets = torch.as_tensor(targets, dtype=torch.float32).to(self.device)
 27%|██████████████████████████████████████▋                                                                                                          | 8/30 [14:39<24:06, 65.76s/it]

In [ ]:
scores_df = model.predict(valid_df.head(), activation_layer="sigmoid")
scores_df.head()